# Data configuration parameters
# This file contains configurations for data loading, preprocessing, and feature engineering

# Data paths
data:
  output_dir: "C:/Users/trgrd/OneDrive/Master/Code/data/processed"  # Directory to store processed data

# Preprocessing parameters
preprocessing:
  levels: 10               # Number of LOB levels to consider
  convert_timestamps: false  # Whether to convert timestamp strings to datetime objects
  timestamp_col: "time"     # Name of the timestamp column
  add_mid_price: false       # Whether to add mid-price column if not present
  winsorize: true          # Whether to winsorize data to remove extreme values
  winsorize_quantiles: [0.001, 0.999]  # Quantiles for winsorizing
  clean_outliers: false      # Whether to remove outliers based on spread
  
# Feature engineering parameters
features:
  ofi:
    enabled: true           # Whether to calculate Order Flow Imbalance features
    levels: 10              # Number of levels for OFI calculation
  
  alpha_term_structure:
    enabled: true           # Whether to calculate alpha term structure
    latency_ms: 50          # Latency buffer in milliseconds
    num_horizons: 10        # Number of prediction horizons

# Data splitting parameters
splitting:
  train_ratio: 0.8          # Ratio of data to use for training
  val_ratio: 0.1            # Ratio of data to use for validation
  test_ratio: 0.1           # Ratio of data to use for testing
  shuffle: false            # Whether to shuffle the data (typically False for time series)
  random_state: 666          # Random seed for reproducibility

# Sequence parameters for model input
sequence:
  length: 100               # Sequence length for CNN/LSTM input
  stride: 1                 # Stride for sequence creation

# Visualization parameters
visualization:
  enabled: true             # Whether to generate visualizations
  sample_size: 10000        # Number of samples to use for visualization
  save_dir: "../results/figures"  # Directory to save visualizations